resolution
Wedyarit/moon-sun pull request #1
Opened 2024-02-13 17:09 UTC by bob302

Added support for scaling objects for different resolutions

2024-02-13 17:10 UTC, bob302 commented
//TODO Фиксануть оцентровку текста, немного подправить константы, чтобы поле было не во весь экран

2024-02-13 19:23 UTC, bob302 commented
Фиксанул оцентровку, и набросал фигни с бгшкой, надо будет подчистить

2024-02-13 19:36 UTC, bob302 commented
Oops

2024-02-13 20:41 UTC, Wedyarit requested changes

2024-02-13 20:41 UTC, Wedyarit commented on src/main.rs
> +                .maximized(true)
I assume there is no need to set the default maximum window size. Window size should be comfort.

2024-02-13 20:41 UTC, Wedyarit commented on src/game.rs
> +    fn set_target_background_color(&mut self, target_color: Color, duration: f32) {
method `set_target_background_color` is never used

2024-02-13 20:41 UTC, Wedyarit commented on src/game.rs
> +use ggez::graphics::{Color, Drawable, Text, TextFragment};
unused import: `Drawable`

2024-02-13 20:41 UTC, Wedyarit commented on src/game.rs
> +use ggez::timer;
unused import: `ggez::timer`

2024-02-13 20:41 UTC, Wedyarit commented on src/game.rs
> +use ggez::mint::Point2;
unused import: `ggez::mint::Point2`

2024-02-13 20:41 UTC, Wedyarit commented on src/game.rs
> +use std::fmt::Alignment;
unused import: `std::fmt::Alignment`

2024-02-19 17:38 UTC, bob302 commented
Тебе не впадлу было unused импорты смотреть?
[Переезд](https://github.com/Wedyarit/moon-sun/pull/2)

2024-02-19 17:38 UTC, closed without merging